### ISSUE TITLE
Natures Prophet can not cast sprout on enemy heros!

### ISSUE THREAD

**Issue by mo-han** [arcadia-redux/12v12#97]
I see the latest update just disabled sprout on allies, when trying to cast, it warns "help disabled".

But the bugs are really wide. When trying to cast on any enemy hero, no go, "help disabled". Even When trying to learn the sprout skill by hit `Ctrl+Q`, no go, "help disabled". Bro, your map is really buggy.

**Comment by darklordabc** [comment]
Hm that's not good. @Sheodar can you check this out

**Comment by mo-han** [comment]
Cannot even sprout on allied creeps.

**Comment by Sheodar** [comment]
Np can use it in enemy, but didn't use it in youself, i fixed it in 4d9b84147908924f60ae7633d825a6405d89e87c

**Comment by mo-han** [comment]
@Sheodar 
Not really, a lot of old issues are still there. For example, if a enemy hero is near your ally creeps, there will be a high chance to not able to sprout on that hero. There are a lot of different situations when unable to sprout on enemies, but none of them is 100% reproducible, so sorry for the lack of details and complete list of them.

The key point is that, the anti-sprout-rolling code you added into the lua script, is trying to do something more than it seems to. This is not a simple feature, and the bugs caused by it can not be intuitively speculated by the logic behind its code.

So, you either need a lot of time to debug it, which means tons of time to play in the game to catch all of those random bugs, or, just remove it. I'm not trying to frustrate you, as some of the related bugs are already fixed, but seriously, I can't see any possibility that you can completely fix this.

**Comment by Sheodar** [comment]
I can fix problem, if i see problem. I saw only one problem, if u use sprouts in teammate (TARGETING using), but enemy next to him, so u cannot easily use sprouts on enemy if an ally is nearby. But i really didn't see other problem. I can fix this problem too, but i don't know, whether to do it. But if people say only "u cannot use it on enemy", i cannot understendt it. I went in lobby and all worked fine.

**Comment by darklordabc** [comment]
FYI the current 12v12 is now currently uploaded, we reverted to an old version because of a bug.

**Comment by mo-han** [comment]
Not fixed, those bugs in #98 are still alive.
Still high chance unable to sprout on enemy heroes.
Even higher chance unable to learn or upgrade the sprout skill.

**Comment by darklordabc** [comment]
Fixed?

**Comment by mo-han** [comment]
Not 100% fixed.
In my last 4 games, there was one of them, during which the bug happened once, only once. When that happened, there was about 5 seconds duration, when I tried and failed to sprout an enemy hero, with the "disable help" warning.
Maybe there is still some minor logic bug in the code.

**Comment by Sheodar** [comment]
Fixed. Reopen if that still a problem
